
include($$PWD/shared/shared.pri)
#include($$PWD/log/log.pri)
include($$PWD/log4qt/log4qt.pri)
include($$PWD/style/style.pri)
include($$PWD/spring/spring.pri)
include($$PWD/socket/socket.pri)
include($$PWD/widgets/widgets.pri)
include($$PWD/toast/toast.pri)
include($$PWD/tools/tools.pri)
#include($$PWD/json_convert/json_convert.pri)
#include($$PWD/sqlite/sqlite.pri)
